name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Go 1.14
#       uses: actions/setup-go@v2
#       with:
#         go-version: 1.14
#       id: go
#     - name: Test
#       run: go test -coverprofile=cover.out ./...

  deploy:
    name: Deploy Dev
    runs-on: ubuntu-latest
#     if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init -input=false tf/

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=out.tfplan $GITHUB_WORKSPACE/tf/
        with:
          service_account_key: ${{ secrets.DEV_GCP_SA_KEY }}
          export_default_credentials: true

      - name: Terraform Apply
        id: tf-apply
        run: terraform apply -out=plan.tfplan -var="api_docker_image=gcr.io/google-samples/hello-app:2.0" $GITHUB_WORKSPACE/tf/



# https://github.com/otrego/clamshell/settings/secrets/new
# https://github.com/GoogleCloudPlatform/github-actions
  # deploy:
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
  #     with:
  #       version: '290.0.1'
  #       project_id: ${{ secrets.DEV_GCP_PROJECT_ID }}
  #       service_account_key: ${{ secrets.DEV_GCP_SA_KEY }}
  #       export_default_credentials: true
  #   - run: gcloud info
